# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asr.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'asr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tasr.proto\x12\x03\x61sr\"\x84\x01\n\nAudioChunk\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07room_id\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x0b\n\x03pcm\x18\x04 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x05 \x01(\x05\x12\x0f\n\x07is_last\x18\x06 \x01(\x08\x12\x0b\n\x03seq\x18\x07 \x01(\x03\"{\n\x14TranscriptAudioChunk\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07room_id\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t\x12\x10\n\x08is_final\x18\x05 \x01(\x08\x12\x0b\n\x03seq\x18\x06 \x01(\x03\x32T\n\nAsrService\x12\x46\n\x14RecognizeAudioStream\x12\x0f.asr.AudioChunk\x1a\x19.asr.TranscriptAudioChunk(\x01\x30\x01\x42\x19Z\x17\x65\x63hat-backend/proto/asrb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027echat-backend/proto/asr'
  _globals['_AUDIOCHUNK']._serialized_start=19
  _globals['_AUDIOCHUNK']._serialized_end=151
  _globals['_TRANSCRIPTAUDIOCHUNK']._serialized_start=153
  _globals['_TRANSCRIPTAUDIOCHUNK']._serialized_end=276
  _globals['_ASRSERVICE']._serialized_start=278
  _globals['_ASRSERVICE']._serialized_end=362
# @@protoc_insertion_point(module_scope)
