# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vad.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'vad.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvad.proto\x12\x03vad\".\n\nVadRequest\x12\x0b\n\x03pcm\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\",\n\x0bVadResponse\x12\x0e\n\x06speech\x18\x01 \x01(\x08\x12\r\n\x05score\x18\x02 \x01(\x02\x32<\n\nVadService\x12.\n\tVadDetect\x12\x0f.vad.VadRequest\x1a\x10.vad.VadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vad_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VADREQUEST']._serialized_start=18
  _globals['_VADREQUEST']._serialized_end=64
  _globals['_VADRESPONSE']._serialized_start=66
  _globals['_VADRESPONSE']._serialized_end=110
  _globals['_VADSERVICE']._serialized_start=112
  _globals['_VADSERVICE']._serialized_end=172
# @@protoc_insertion_point(module_scope)
