// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"echat-backend/ent/authtoken"
	"echat-backend/ent/predicate"
	"echat-backend/ent/user"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AuthTokenUpdate is the builder for updating AuthToken entities.
type AuthTokenUpdate struct {
	config
	hooks    []Hook
	mutation *AuthTokenMutation
}

// Where appends a list predicates to the AuthTokenUpdate builder.
func (_u *AuthTokenUpdate) Where(ps ...predicate.AuthToken) *AuthTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuthTokenUpdate) SetUserID(v uuid.UUID) *AuthTokenUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuthTokenUpdate) SetNillableUserID(v *uuid.UUID) *AuthTokenUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPurpose sets the "purpose" field.
func (_u *AuthTokenUpdate) SetPurpose(v authtoken.Purpose) *AuthTokenUpdate {
	_u.mutation.SetPurpose(v)
	return _u
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_u *AuthTokenUpdate) SetNillablePurpose(v *authtoken.Purpose) *AuthTokenUpdate {
	if v != nil {
		_u.SetPurpose(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *AuthTokenUpdate) SetTokenHash(v string) *AuthTokenUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *AuthTokenUpdate) SetNillableTokenHash(v *string) *AuthTokenUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthTokenUpdate) SetExpiresAt(v time.Time) *AuthTokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthTokenUpdate) SetNillableExpiresAt(v *time.Time) *AuthTokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *AuthTokenUpdate) SetConsumedAt(v time.Time) *AuthTokenUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *AuthTokenUpdate) SetNillableConsumedAt(v *time.Time) *AuthTokenUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *AuthTokenUpdate) ClearConsumedAt() *AuthTokenUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AuthTokenUpdate) SetUser(v *User) *AuthTokenUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AuthTokenMutation object of the builder.
func (_u *AuthTokenUpdate) Mutation() *AuthTokenMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AuthTokenUpdate) ClearUser() *AuthTokenUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthTokenUpdate) check() error {
	if v, ok := _u.mutation.Purpose(); ok {
		if err := authtoken.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "AuthToken.purpose": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AuthToken.user"`)
	}
	return nil
}

func (_u *AuthTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authtoken.Table, authtoken.Columns, sqlgraph.NewFieldSpec(authtoken.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Purpose(); ok {
		_spec.SetField(authtoken.FieldPurpose, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(authtoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authtoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(authtoken.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(authtoken.FieldConsumedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authtoken.UserTable,
			Columns: []string{authtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authtoken.UserTable,
			Columns: []string{authtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthTokenUpdateOne is the builder for updating a single AuthToken entity.
type AuthTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthTokenMutation
}

// SetUserID sets the "user_id" field.
func (_u *AuthTokenUpdateOne) SetUserID(v uuid.UUID) *AuthTokenUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuthTokenUpdateOne) SetNillableUserID(v *uuid.UUID) *AuthTokenUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPurpose sets the "purpose" field.
func (_u *AuthTokenUpdateOne) SetPurpose(v authtoken.Purpose) *AuthTokenUpdateOne {
	_u.mutation.SetPurpose(v)
	return _u
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_u *AuthTokenUpdateOne) SetNillablePurpose(v *authtoken.Purpose) *AuthTokenUpdateOne {
	if v != nil {
		_u.SetPurpose(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *AuthTokenUpdateOne) SetTokenHash(v string) *AuthTokenUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *AuthTokenUpdateOne) SetNillableTokenHash(v *string) *AuthTokenUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthTokenUpdateOne) SetExpiresAt(v time.Time) *AuthTokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthTokenUpdateOne) SetNillableExpiresAt(v *time.Time) *AuthTokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *AuthTokenUpdateOne) SetConsumedAt(v time.Time) *AuthTokenUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *AuthTokenUpdateOne) SetNillableConsumedAt(v *time.Time) *AuthTokenUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *AuthTokenUpdateOne) ClearConsumedAt() *AuthTokenUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AuthTokenUpdateOne) SetUser(v *User) *AuthTokenUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AuthTokenMutation object of the builder.
func (_u *AuthTokenUpdateOne) Mutation() *AuthTokenMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AuthTokenUpdateOne) ClearUser() *AuthTokenUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the AuthTokenUpdate builder.
func (_u *AuthTokenUpdateOne) Where(ps ...predicate.AuthToken) *AuthTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthTokenUpdateOne) Select(field string, fields ...string) *AuthTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthToken entity.
func (_u *AuthTokenUpdateOne) Save(ctx context.Context) (*AuthToken, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthTokenUpdateOne) SaveX(ctx context.Context) *AuthToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthTokenUpdateOne) check() error {
	if v, ok := _u.mutation.Purpose(); ok {
		if err := authtoken.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "AuthToken.purpose": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AuthToken.user"`)
	}
	return nil
}

func (_u *AuthTokenUpdateOne) sqlSave(ctx context.Context) (_node *AuthToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authtoken.Table, authtoken.Columns, sqlgraph.NewFieldSpec(authtoken.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authtoken.FieldID)
		for _, f := range fields {
			if !authtoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Purpose(); ok {
		_spec.SetField(authtoken.FieldPurpose, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(authtoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authtoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(authtoken.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(authtoken.FieldConsumedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authtoken.UserTable,
			Columns: []string{authtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authtoken.UserTable,
			Columns: []string{authtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AuthToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
