// Code generated by ent, DO NOT EDIT.

package ent

import (
	"echat-backend/ent/outboxevent"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// OutboxEvent is the model entity for the OutboxEvent schema.
type OutboxEvent struct {
	config `json:"-"`
	// ID of the ent.
	// 事件主键，写入时由服务端生成
	ID uuid.UUID `json:"id,omitempty"`
	// 事件类型枚举，如 user.registered / user.login.succeeded
	EventType string `json:"event_type,omitempty"`
	// 聚合根 id，如 user_id，供下游按实例归集
	AggregateID uuid.UUID `json:"aggregate_id,omitempty"`
	// 事件骨干 subject，如 user.{id}.registered
	Subject string `json:"subject,omitempty"`
	// 事件载荷 jsonb，可空
	Payload map[string]interface{} `json:"payload,omitempty"`
	// 投递状态机：pending / sent / failed
	Status outboxevent.Status `json:"status,omitempty"`
	// 事件记账时间
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OutboxEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case outboxevent.FieldPayload:
			values[i] = new([]byte)
		case outboxevent.FieldEventType, outboxevent.FieldSubject, outboxevent.FieldStatus:
			values[i] = new(sql.NullString)
		case outboxevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case outboxevent.FieldID, outboxevent.FieldAggregateID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OutboxEvent fields.
func (_m *OutboxEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case outboxevent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case outboxevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case outboxevent.FieldAggregateID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field aggregate_id", values[i])
			} else if value != nil {
				_m.AggregateID = *value
			}
		case outboxevent.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				_m.Subject = value.String
			}
		case outboxevent.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case outboxevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = outboxevent.Status(value.String)
			}
		case outboxevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OutboxEvent.
// This includes values selected through modifiers, order, etc.
func (_m *OutboxEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OutboxEvent.
// Note that you need to call OutboxEvent.Unwrap() before calling this method if this OutboxEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OutboxEvent) Update() *OutboxEventUpdateOne {
	return NewOutboxEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OutboxEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OutboxEvent) Unwrap() *OutboxEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OutboxEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OutboxEvent) String() string {
	var builder strings.Builder
	builder.WriteString("OutboxEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("aggregate_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AggregateID))
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(_m.Subject)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OutboxEvents is a parsable slice of OutboxEvent.
type OutboxEvents []*OutboxEvent
