// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"echat-backend/ent/predicate"
	"echat-backend/ent/roommember"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RoomMemberDelete is the builder for deleting a RoomMember entity.
type RoomMemberDelete struct {
	config
	hooks    []Hook
	mutation *RoomMemberMutation
}

// Where appends a list predicates to the RoomMemberDelete builder.
func (_d *RoomMemberDelete) Where(ps ...predicate.RoomMember) *RoomMemberDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RoomMemberDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RoomMemberDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RoomMemberDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(roommember.Table, sqlgraph.NewFieldSpec(roommember.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RoomMemberDeleteOne is the builder for deleting a single RoomMember entity.
type RoomMemberDeleteOne struct {
	_d *RoomMemberDelete
}

// Where appends a list predicates to the RoomMemberDelete builder.
func (_d *RoomMemberDeleteOne) Where(ps ...predicate.RoomMember) *RoomMemberDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RoomMemberDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{roommember.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RoomMemberDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
