// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"echat-backend/ent/room"
	"echat-backend/ent/roommember"
	"echat-backend/ent/user"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RoomMemberCreate is the builder for creating a RoomMember entity.
type RoomMemberCreate struct {
	config
	mutation *RoomMemberMutation
	hooks    []Hook
}

// SetRoomID sets the "room_id" field.
func (_c *RoomMemberCreate) SetRoomID(v uuid.UUID) *RoomMemberCreate {
	_c.mutation.SetRoomID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RoomMemberCreate) SetUserID(v uuid.UUID) *RoomMemberCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetUsername sets the "username" field.
func (_c *RoomMemberCreate) SetUsername(v string) *RoomMemberCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetJoinedAt sets the "joined_at" field.
func (_c *RoomMemberCreate) SetJoinedAt(v time.Time) *RoomMemberCreate {
	_c.mutation.SetJoinedAt(v)
	return _c
}

// SetLeftAt sets the "left_at" field.
func (_c *RoomMemberCreate) SetLeftAt(v time.Time) *RoomMemberCreate {
	_c.mutation.SetLeftAt(v)
	return _c
}

// SetNillableLeftAt sets the "left_at" field if the given value is not nil.
func (_c *RoomMemberCreate) SetNillableLeftAt(v *time.Time) *RoomMemberCreate {
	if v != nil {
		_c.SetLeftAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RoomMemberCreate) SetID(v uuid.UUID) *RoomMemberCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetRoom sets the "room" edge to the Room entity.
func (_c *RoomMemberCreate) SetRoom(v *Room) *RoomMemberCreate {
	return _c.SetRoomID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *RoomMemberCreate) SetUser(v *User) *RoomMemberCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the RoomMemberMutation object of the builder.
func (_c *RoomMemberCreate) Mutation() *RoomMemberMutation {
	return _c.mutation
}

// Save creates the RoomMember in the database.
func (_c *RoomMemberCreate) Save(ctx context.Context) (*RoomMember, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RoomMemberCreate) SaveX(ctx context.Context) *RoomMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoomMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoomMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RoomMemberCreate) check() error {
	if _, ok := _c.mutation.RoomID(); !ok {
		return &ValidationError{Name: "room_id", err: errors.New(`ent: missing required field "RoomMember.room_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RoomMember.user_id"`)}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "RoomMember.username"`)}
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		return &ValidationError{Name: "joined_at", err: errors.New(`ent: missing required field "RoomMember.joined_at"`)}
	}
	if len(_c.mutation.RoomIDs()) == 0 {
		return &ValidationError{Name: "room", err: errors.New(`ent: missing required edge "RoomMember.room"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "RoomMember.user"`)}
	}
	return nil
}

func (_c *RoomMemberCreate) sqlSave(ctx context.Context) (*RoomMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RoomMemberCreate) createSpec() (*RoomMember, *sqlgraph.CreateSpec) {
	var (
		_node = &RoomMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(roommember.Table, sqlgraph.NewFieldSpec(roommember.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(roommember.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.JoinedAt(); ok {
		_spec.SetField(roommember.FieldJoinedAt, field.TypeTime, value)
		_node.JoinedAt = value
	}
	if value, ok := _c.mutation.LeftAt(); ok {
		_spec.SetField(roommember.FieldLeftAt, field.TypeTime, value)
		_node.LeftAt = &value
	}
	if nodes := _c.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roommember.RoomTable,
			Columns: []string{roommember.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoomID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roommember.UserTable,
			Columns: []string{roommember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RoomMemberCreateBulk is the builder for creating many RoomMember entities in bulk.
type RoomMemberCreateBulk struct {
	config
	err      error
	builders []*RoomMemberCreate
}

// Save creates the RoomMember entities in the database.
func (_c *RoomMemberCreateBulk) Save(ctx context.Context) ([]*RoomMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RoomMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoomMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RoomMemberCreateBulk) SaveX(ctx context.Context) []*RoomMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoomMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoomMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
