// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"echat-backend/ent/predicate"
	"echat-backend/ent/room"
	"echat-backend/ent/roommember"
	"echat-backend/ent/user"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RoomMemberUpdate is the builder for updating RoomMember entities.
type RoomMemberUpdate struct {
	config
	hooks    []Hook
	mutation *RoomMemberMutation
}

// Where appends a list predicates to the RoomMemberUpdate builder.
func (_u *RoomMemberUpdate) Where(ps ...predicate.RoomMember) *RoomMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRoomID sets the "room_id" field.
func (_u *RoomMemberUpdate) SetRoomID(v uuid.UUID) *RoomMemberUpdate {
	_u.mutation.SetRoomID(v)
	return _u
}

// SetNillableRoomID sets the "room_id" field if the given value is not nil.
func (_u *RoomMemberUpdate) SetNillableRoomID(v *uuid.UUID) *RoomMemberUpdate {
	if v != nil {
		_u.SetRoomID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RoomMemberUpdate) SetUserID(v uuid.UUID) *RoomMemberUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RoomMemberUpdate) SetNillableUserID(v *uuid.UUID) *RoomMemberUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *RoomMemberUpdate) SetUsername(v string) *RoomMemberUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *RoomMemberUpdate) SetNillableUsername(v *string) *RoomMemberUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *RoomMemberUpdate) SetJoinedAt(v time.Time) *RoomMemberUpdate {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *RoomMemberUpdate) SetNillableJoinedAt(v *time.Time) *RoomMemberUpdate {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// SetLeftAt sets the "left_at" field.
func (_u *RoomMemberUpdate) SetLeftAt(v time.Time) *RoomMemberUpdate {
	_u.mutation.SetLeftAt(v)
	return _u
}

// SetNillableLeftAt sets the "left_at" field if the given value is not nil.
func (_u *RoomMemberUpdate) SetNillableLeftAt(v *time.Time) *RoomMemberUpdate {
	if v != nil {
		_u.SetLeftAt(*v)
	}
	return _u
}

// ClearLeftAt clears the value of the "left_at" field.
func (_u *RoomMemberUpdate) ClearLeftAt() *RoomMemberUpdate {
	_u.mutation.ClearLeftAt()
	return _u
}

// SetRoom sets the "room" edge to the Room entity.
func (_u *RoomMemberUpdate) SetRoom(v *Room) *RoomMemberUpdate {
	return _u.SetRoomID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *RoomMemberUpdate) SetUser(v *User) *RoomMemberUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the RoomMemberMutation object of the builder.
func (_u *RoomMemberUpdate) Mutation() *RoomMemberMutation {
	return _u.mutation
}

// ClearRoom clears the "room" edge to the Room entity.
func (_u *RoomMemberUpdate) ClearRoom() *RoomMemberUpdate {
	_u.mutation.ClearRoom()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RoomMemberUpdate) ClearUser() *RoomMemberUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RoomMemberUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoomMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RoomMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoomMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoomMemberUpdate) check() error {
	if _u.mutation.RoomCleared() && len(_u.mutation.RoomIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RoomMember.room"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RoomMember.user"`)
	}
	return nil
}

func (_u *RoomMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(roommember.Table, roommember.Columns, sqlgraph.NewFieldSpec(roommember.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(roommember.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(roommember.FieldJoinedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LeftAt(); ok {
		_spec.SetField(roommember.FieldLeftAt, field.TypeTime, value)
	}
	if _u.mutation.LeftAtCleared() {
		_spec.ClearField(roommember.FieldLeftAt, field.TypeTime)
	}
	if _u.mutation.RoomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roommember.RoomTable,
			Columns: []string{roommember.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roommember.RoomTable,
			Columns: []string{roommember.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roommember.UserTable,
			Columns: []string{roommember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roommember.UserTable,
			Columns: []string{roommember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roommember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RoomMemberUpdateOne is the builder for updating a single RoomMember entity.
type RoomMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoomMemberMutation
}

// SetRoomID sets the "room_id" field.
func (_u *RoomMemberUpdateOne) SetRoomID(v uuid.UUID) *RoomMemberUpdateOne {
	_u.mutation.SetRoomID(v)
	return _u
}

// SetNillableRoomID sets the "room_id" field if the given value is not nil.
func (_u *RoomMemberUpdateOne) SetNillableRoomID(v *uuid.UUID) *RoomMemberUpdateOne {
	if v != nil {
		_u.SetRoomID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RoomMemberUpdateOne) SetUserID(v uuid.UUID) *RoomMemberUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RoomMemberUpdateOne) SetNillableUserID(v *uuid.UUID) *RoomMemberUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *RoomMemberUpdateOne) SetUsername(v string) *RoomMemberUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *RoomMemberUpdateOne) SetNillableUsername(v *string) *RoomMemberUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *RoomMemberUpdateOne) SetJoinedAt(v time.Time) *RoomMemberUpdateOne {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *RoomMemberUpdateOne) SetNillableJoinedAt(v *time.Time) *RoomMemberUpdateOne {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// SetLeftAt sets the "left_at" field.
func (_u *RoomMemberUpdateOne) SetLeftAt(v time.Time) *RoomMemberUpdateOne {
	_u.mutation.SetLeftAt(v)
	return _u
}

// SetNillableLeftAt sets the "left_at" field if the given value is not nil.
func (_u *RoomMemberUpdateOne) SetNillableLeftAt(v *time.Time) *RoomMemberUpdateOne {
	if v != nil {
		_u.SetLeftAt(*v)
	}
	return _u
}

// ClearLeftAt clears the value of the "left_at" field.
func (_u *RoomMemberUpdateOne) ClearLeftAt() *RoomMemberUpdateOne {
	_u.mutation.ClearLeftAt()
	return _u
}

// SetRoom sets the "room" edge to the Room entity.
func (_u *RoomMemberUpdateOne) SetRoom(v *Room) *RoomMemberUpdateOne {
	return _u.SetRoomID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *RoomMemberUpdateOne) SetUser(v *User) *RoomMemberUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the RoomMemberMutation object of the builder.
func (_u *RoomMemberUpdateOne) Mutation() *RoomMemberMutation {
	return _u.mutation
}

// ClearRoom clears the "room" edge to the Room entity.
func (_u *RoomMemberUpdateOne) ClearRoom() *RoomMemberUpdateOne {
	_u.mutation.ClearRoom()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RoomMemberUpdateOne) ClearUser() *RoomMemberUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the RoomMemberUpdate builder.
func (_u *RoomMemberUpdateOne) Where(ps ...predicate.RoomMember) *RoomMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RoomMemberUpdateOne) Select(field string, fields ...string) *RoomMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RoomMember entity.
func (_u *RoomMemberUpdateOne) Save(ctx context.Context) (*RoomMember, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoomMemberUpdateOne) SaveX(ctx context.Context) *RoomMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RoomMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoomMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoomMemberUpdateOne) check() error {
	if _u.mutation.RoomCleared() && len(_u.mutation.RoomIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RoomMember.room"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RoomMember.user"`)
	}
	return nil
}

func (_u *RoomMemberUpdateOne) sqlSave(ctx context.Context) (_node *RoomMember, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(roommember.Table, roommember.Columns, sqlgraph.NewFieldSpec(roommember.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RoomMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, roommember.FieldID)
		for _, f := range fields {
			if !roommember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != roommember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(roommember.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(roommember.FieldJoinedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LeftAt(); ok {
		_spec.SetField(roommember.FieldLeftAt, field.TypeTime, value)
	}
	if _u.mutation.LeftAtCleared() {
		_spec.ClearField(roommember.FieldLeftAt, field.TypeTime)
	}
	if _u.mutation.RoomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roommember.RoomTable,
			Columns: []string{roommember.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roommember.RoomTable,
			Columns: []string{roommember.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roommember.UserTable,
			Columns: []string{roommember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roommember.UserTable,
			Columns: []string{roommember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RoomMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roommember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
