// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"echat-backend/ent/predicate"
	"echat-backend/ent/room"
	"echat-backend/ent/roommember"
	"echat-backend/ent/user"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RoomUpdate is the builder for updating Room entities.
type RoomUpdate struct {
	config
	hooks    []Hook
	mutation *RoomMutation
}

// Where appends a list predicates to the RoomUpdate builder.
func (_u *RoomUpdate) Where(ps ...predicate.Room) *RoomUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetHostID sets the "host_id" field.
func (_u *RoomUpdate) SetHostID(v uuid.UUID) *RoomUpdate {
	_u.mutation.SetHostID(v)
	return _u
}

// SetNillableHostID sets the "host_id" field if the given value is not nil.
func (_u *RoomUpdate) SetNillableHostID(v *uuid.UUID) *RoomUpdate {
	if v != nil {
		_u.SetHostID(*v)
	}
	return _u
}

// SetRoomCode sets the "room_code" field.
func (_u *RoomUpdate) SetRoomCode(v string) *RoomUpdate {
	_u.mutation.SetRoomCode(v)
	return _u
}

// SetNillableRoomCode sets the "room_code" field if the given value is not nil.
func (_u *RoomUpdate) SetNillableRoomCode(v *string) *RoomUpdate {
	if v != nil {
		_u.SetRoomCode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RoomUpdate) SetStatus(v room.Status) *RoomUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RoomUpdate) SetNillableStatus(v *room.Status) *RoomUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *RoomUpdate) SetClosedAt(v time.Time) *RoomUpdate {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *RoomUpdate) SetNillableClosedAt(v *time.Time) *RoomUpdate {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *RoomUpdate) ClearClosedAt() *RoomUpdate {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RoomUpdate) SetUpdatedAt(v time.Time) *RoomUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetHost sets the "host" edge to the User entity.
func (_u *RoomUpdate) SetHost(v *User) *RoomUpdate {
	return _u.SetHostID(v.ID)
}

// AddMembershipIDs adds the "memberships" edge to the RoomMember entity by IDs.
func (_u *RoomUpdate) AddMembershipIDs(ids ...uuid.UUID) *RoomUpdate {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the RoomMember entity.
func (_u *RoomUpdate) AddMemberships(v ...*RoomMember) *RoomUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// Mutation returns the RoomMutation object of the builder.
func (_u *RoomUpdate) Mutation() *RoomMutation {
	return _u.mutation
}

// ClearHost clears the "host" edge to the User entity.
func (_u *RoomUpdate) ClearHost() *RoomUpdate {
	_u.mutation.ClearHost()
	return _u
}

// ClearMemberships clears all "memberships" edges to the RoomMember entity.
func (_u *RoomUpdate) ClearMemberships() *RoomUpdate {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to RoomMember entities by IDs.
func (_u *RoomUpdate) RemoveMembershipIDs(ids ...uuid.UUID) *RoomUpdate {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to RoomMember entities.
func (_u *RoomUpdate) RemoveMemberships(v ...*RoomMember) *RoomUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RoomUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoomUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RoomUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoomUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RoomUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := room.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoomUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := room.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Room.status": %w`, err)}
		}
	}
	if _u.mutation.HostCleared() && len(_u.mutation.HostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Room.host"`)
	}
	return nil
}

func (_u *RoomUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(room.Table, room.Columns, sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RoomCode(); ok {
		_spec.SetField(room.FieldRoomCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(room.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(room.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(room.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(room.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.HostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.HostTable,
			Columns: []string{room.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.HostTable,
			Columns: []string{room.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.MembershipsTable,
			Columns: []string{room.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roommember.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.MembershipsTable,
			Columns: []string{room.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roommember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.MembershipsTable,
			Columns: []string{room.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roommember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{room.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RoomUpdateOne is the builder for updating a single Room entity.
type RoomUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoomMutation
}

// SetHostID sets the "host_id" field.
func (_u *RoomUpdateOne) SetHostID(v uuid.UUID) *RoomUpdateOne {
	_u.mutation.SetHostID(v)
	return _u
}

// SetNillableHostID sets the "host_id" field if the given value is not nil.
func (_u *RoomUpdateOne) SetNillableHostID(v *uuid.UUID) *RoomUpdateOne {
	if v != nil {
		_u.SetHostID(*v)
	}
	return _u
}

// SetRoomCode sets the "room_code" field.
func (_u *RoomUpdateOne) SetRoomCode(v string) *RoomUpdateOne {
	_u.mutation.SetRoomCode(v)
	return _u
}

// SetNillableRoomCode sets the "room_code" field if the given value is not nil.
func (_u *RoomUpdateOne) SetNillableRoomCode(v *string) *RoomUpdateOne {
	if v != nil {
		_u.SetRoomCode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RoomUpdateOne) SetStatus(v room.Status) *RoomUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RoomUpdateOne) SetNillableStatus(v *room.Status) *RoomUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *RoomUpdateOne) SetClosedAt(v time.Time) *RoomUpdateOne {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *RoomUpdateOne) SetNillableClosedAt(v *time.Time) *RoomUpdateOne {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *RoomUpdateOne) ClearClosedAt() *RoomUpdateOne {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RoomUpdateOne) SetUpdatedAt(v time.Time) *RoomUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetHost sets the "host" edge to the User entity.
func (_u *RoomUpdateOne) SetHost(v *User) *RoomUpdateOne {
	return _u.SetHostID(v.ID)
}

// AddMembershipIDs adds the "memberships" edge to the RoomMember entity by IDs.
func (_u *RoomUpdateOne) AddMembershipIDs(ids ...uuid.UUID) *RoomUpdateOne {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the RoomMember entity.
func (_u *RoomUpdateOne) AddMemberships(v ...*RoomMember) *RoomUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// Mutation returns the RoomMutation object of the builder.
func (_u *RoomUpdateOne) Mutation() *RoomMutation {
	return _u.mutation
}

// ClearHost clears the "host" edge to the User entity.
func (_u *RoomUpdateOne) ClearHost() *RoomUpdateOne {
	_u.mutation.ClearHost()
	return _u
}

// ClearMemberships clears all "memberships" edges to the RoomMember entity.
func (_u *RoomUpdateOne) ClearMemberships() *RoomUpdateOne {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to RoomMember entities by IDs.
func (_u *RoomUpdateOne) RemoveMembershipIDs(ids ...uuid.UUID) *RoomUpdateOne {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to RoomMember entities.
func (_u *RoomUpdateOne) RemoveMemberships(v ...*RoomMember) *RoomUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// Where appends a list predicates to the RoomUpdate builder.
func (_u *RoomUpdateOne) Where(ps ...predicate.Room) *RoomUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RoomUpdateOne) Select(field string, fields ...string) *RoomUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Room entity.
func (_u *RoomUpdateOne) Save(ctx context.Context) (*Room, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoomUpdateOne) SaveX(ctx context.Context) *Room {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RoomUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoomUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RoomUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := room.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoomUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := room.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Room.status": %w`, err)}
		}
	}
	if _u.mutation.HostCleared() && len(_u.mutation.HostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Room.host"`)
	}
	return nil
}

func (_u *RoomUpdateOne) sqlSave(ctx context.Context) (_node *Room, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(room.Table, room.Columns, sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Room.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, room.FieldID)
		for _, f := range fields {
			if !room.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != room.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RoomCode(); ok {
		_spec.SetField(room.FieldRoomCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(room.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(room.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(room.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(room.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.HostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.HostTable,
			Columns: []string{room.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.HostTable,
			Columns: []string{room.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.MembershipsTable,
			Columns: []string{room.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roommember.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.MembershipsTable,
			Columns: []string{room.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roommember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.MembershipsTable,
			Columns: []string{room.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roommember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Room{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{room.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
