// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"echat-backend/ent/predicate"
	"echat-backend/ent/session"
	"echat-backend/ent/user"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SessionUpdate is the builder for updating Session entities.
type SessionUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdate) Where(ps ...predicate.Session) *SessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SessionUpdate) SetUserID(v uuid.UUID) *SessionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableUserID(v *uuid.UUID) *SessionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRefreshTokenHash sets the "refresh_token_hash" field.
func (_u *SessionUpdate) SetRefreshTokenHash(v string) *SessionUpdate {
	_u.mutation.SetRefreshTokenHash(v)
	return _u
}

// SetNillableRefreshTokenHash sets the "refresh_token_hash" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableRefreshTokenHash(v *string) *SessionUpdate {
	if v != nil {
		_u.SetRefreshTokenHash(*v)
	}
	return _u
}

// SetTokenVersion sets the "token_version" field.
func (_u *SessionUpdate) SetTokenVersion(v int) *SessionUpdate {
	_u.mutation.ResetTokenVersion()
	_u.mutation.SetTokenVersion(v)
	return _u
}

// SetNillableTokenVersion sets the "token_version" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableTokenVersion(v *int) *SessionUpdate {
	if v != nil {
		_u.SetTokenVersion(*v)
	}
	return _u
}

// AddTokenVersion adds value to the "token_version" field.
func (_u *SessionUpdate) AddTokenVersion(v int) *SessionUpdate {
	_u.mutation.AddTokenVersion(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SessionUpdate) SetExpiresAt(v time.Time) *SessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableExpiresAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *SessionUpdate) SetRevokedAt(v time.Time) *SessionUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableRevokedAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *SessionUpdate) ClearRevokedAt() *SessionUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetIP sets the "ip" field.
func (_u *SessionUpdate) SetIP(v string) *SessionUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableIP(v *string) *SessionUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *SessionUpdate) SetUserAgent(v string) *SessionUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableUserAgent(v *string) *SessionUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *SessionUpdate) ClearUserAgent() *SessionUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetDeviceFingerprint sets the "device_fingerprint" field.
func (_u *SessionUpdate) SetDeviceFingerprint(v string) *SessionUpdate {
	_u.mutation.SetDeviceFingerprint(v)
	return _u
}

// SetNillableDeviceFingerprint sets the "device_fingerprint" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableDeviceFingerprint(v *string) *SessionUpdate {
	if v != nil {
		_u.SetDeviceFingerprint(*v)
	}
	return _u
}

// ClearDeviceFingerprint clears the value of the "device_fingerprint" field.
func (_u *SessionUpdate) ClearDeviceFingerprint() *SessionUpdate {
	_u.mutation.ClearDeviceFingerprint()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SessionUpdate) SetUser(v *User) *SessionUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdate) Mutation() *SessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SessionUpdate) ClearUser() *SessionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Session.user"`)
	}
	return nil
}

func (_u *SessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RefreshTokenHash(); ok {
		_spec.SetField(session.FieldRefreshTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenVersion(); ok {
		_spec.SetField(session.FieldTokenVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenVersion(); ok {
		_spec.AddField(session.FieldTokenVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(session.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(session.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(session.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(session.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(session.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(session.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.DeviceFingerprint(); ok {
		_spec.SetField(session.FieldDeviceFingerprint, field.TypeString, value)
	}
	if _u.mutation.DeviceFingerprintCleared() {
		_spec.ClearField(session.FieldDeviceFingerprint, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.UserTable,
			Columns: []string{session.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.UserTable,
			Columns: []string{session.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SessionUpdateOne is the builder for updating a single Session entity.
type SessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMutation
}

// SetUserID sets the "user_id" field.
func (_u *SessionUpdateOne) SetUserID(v uuid.UUID) *SessionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableUserID(v *uuid.UUID) *SessionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRefreshTokenHash sets the "refresh_token_hash" field.
func (_u *SessionUpdateOne) SetRefreshTokenHash(v string) *SessionUpdateOne {
	_u.mutation.SetRefreshTokenHash(v)
	return _u
}

// SetNillableRefreshTokenHash sets the "refresh_token_hash" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableRefreshTokenHash(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetRefreshTokenHash(*v)
	}
	return _u
}

// SetTokenVersion sets the "token_version" field.
func (_u *SessionUpdateOne) SetTokenVersion(v int) *SessionUpdateOne {
	_u.mutation.ResetTokenVersion()
	_u.mutation.SetTokenVersion(v)
	return _u
}

// SetNillableTokenVersion sets the "token_version" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableTokenVersion(v *int) *SessionUpdateOne {
	if v != nil {
		_u.SetTokenVersion(*v)
	}
	return _u
}

// AddTokenVersion adds value to the "token_version" field.
func (_u *SessionUpdateOne) AddTokenVersion(v int) *SessionUpdateOne {
	_u.mutation.AddTokenVersion(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SessionUpdateOne) SetExpiresAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableExpiresAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *SessionUpdateOne) SetRevokedAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableRevokedAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *SessionUpdateOne) ClearRevokedAt() *SessionUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetIP sets the "ip" field.
func (_u *SessionUpdateOne) SetIP(v string) *SessionUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableIP(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *SessionUpdateOne) SetUserAgent(v string) *SessionUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableUserAgent(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *SessionUpdateOne) ClearUserAgent() *SessionUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetDeviceFingerprint sets the "device_fingerprint" field.
func (_u *SessionUpdateOne) SetDeviceFingerprint(v string) *SessionUpdateOne {
	_u.mutation.SetDeviceFingerprint(v)
	return _u
}

// SetNillableDeviceFingerprint sets the "device_fingerprint" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableDeviceFingerprint(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetDeviceFingerprint(*v)
	}
	return _u
}

// ClearDeviceFingerprint clears the value of the "device_fingerprint" field.
func (_u *SessionUpdateOne) ClearDeviceFingerprint() *SessionUpdateOne {
	_u.mutation.ClearDeviceFingerprint()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SessionUpdateOne) SetUser(v *User) *SessionUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdateOne) Mutation() *SessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SessionUpdateOne) ClearUser() *SessionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdateOne) Where(ps ...predicate.Session) *SessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SessionUpdateOne) Select(field string, fields ...string) *SessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Session entity.
func (_u *SessionUpdateOne) Save(ctx context.Context) (*Session, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdateOne) SaveX(ctx context.Context) *Session {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Session.user"`)
	}
	return nil
}

func (_u *SessionUpdateOne) sqlSave(ctx context.Context) (_node *Session, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Session.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, session.FieldID)
		for _, f := range fields {
			if !session.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != session.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RefreshTokenHash(); ok {
		_spec.SetField(session.FieldRefreshTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenVersion(); ok {
		_spec.SetField(session.FieldTokenVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenVersion(); ok {
		_spec.AddField(session.FieldTokenVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(session.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(session.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(session.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(session.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(session.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(session.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.DeviceFingerprint(); ok {
		_spec.SetField(session.FieldDeviceFingerprint, field.TypeString, value)
	}
	if _u.mutation.DeviceFingerprintCleared() {
		_spec.ClearField(session.FieldDeviceFingerprint, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.UserTable,
			Columns: []string{session.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.UserTable,
			Columns: []string{session.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Session{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
