// Code generated by ent, DO NOT EDIT.

package identity

import (
	"echat-backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Identity {
	return predicate.Identity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Identity {
	return predicate.Identity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Identity {
	return predicate.Identity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Identity {
	return predicate.Identity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Identity {
	return predicate.Identity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Identity {
	return predicate.Identity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Identity {
	return predicate.Identity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Identity {
	return predicate.Identity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Identity {
	return predicate.Identity(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Identity {
	return predicate.Identity(sql.FieldEQ(FieldUserID, v))
}

// ProviderUID applies equality check predicate on the "provider_uid" field. It's identical to ProviderUIDEQ.
func ProviderUID(v string) predicate.Identity {
	return predicate.Identity(sql.FieldEQ(FieldProviderUID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Identity {
	return predicate.Identity(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Identity {
	return predicate.Identity(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Identity {
	return predicate.Identity(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Identity {
	return predicate.Identity(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Identity {
	return predicate.Identity(sql.FieldNotIn(FieldUserID, vs...))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v Provider) predicate.Identity {
	return predicate.Identity(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v Provider) predicate.Identity {
	return predicate.Identity(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...Provider) predicate.Identity {
	return predicate.Identity(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...Provider) predicate.Identity {
	return predicate.Identity(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderUIDEQ applies the EQ predicate on the "provider_uid" field.
func ProviderUIDEQ(v string) predicate.Identity {
	return predicate.Identity(sql.FieldEQ(FieldProviderUID, v))
}

// ProviderUIDNEQ applies the NEQ predicate on the "provider_uid" field.
func ProviderUIDNEQ(v string) predicate.Identity {
	return predicate.Identity(sql.FieldNEQ(FieldProviderUID, v))
}

// ProviderUIDIn applies the In predicate on the "provider_uid" field.
func ProviderUIDIn(vs ...string) predicate.Identity {
	return predicate.Identity(sql.FieldIn(FieldProviderUID, vs...))
}

// ProviderUIDNotIn applies the NotIn predicate on the "provider_uid" field.
func ProviderUIDNotIn(vs ...string) predicate.Identity {
	return predicate.Identity(sql.FieldNotIn(FieldProviderUID, vs...))
}

// ProviderUIDGT applies the GT predicate on the "provider_uid" field.
func ProviderUIDGT(v string) predicate.Identity {
	return predicate.Identity(sql.FieldGT(FieldProviderUID, v))
}

// ProviderUIDGTE applies the GTE predicate on the "provider_uid" field.
func ProviderUIDGTE(v string) predicate.Identity {
	return predicate.Identity(sql.FieldGTE(FieldProviderUID, v))
}

// ProviderUIDLT applies the LT predicate on the "provider_uid" field.
func ProviderUIDLT(v string) predicate.Identity {
	return predicate.Identity(sql.FieldLT(FieldProviderUID, v))
}

// ProviderUIDLTE applies the LTE predicate on the "provider_uid" field.
func ProviderUIDLTE(v string) predicate.Identity {
	return predicate.Identity(sql.FieldLTE(FieldProviderUID, v))
}

// ProviderUIDContains applies the Contains predicate on the "provider_uid" field.
func ProviderUIDContains(v string) predicate.Identity {
	return predicate.Identity(sql.FieldContains(FieldProviderUID, v))
}

// ProviderUIDHasPrefix applies the HasPrefix predicate on the "provider_uid" field.
func ProviderUIDHasPrefix(v string) predicate.Identity {
	return predicate.Identity(sql.FieldHasPrefix(FieldProviderUID, v))
}

// ProviderUIDHasSuffix applies the HasSuffix predicate on the "provider_uid" field.
func ProviderUIDHasSuffix(v string) predicate.Identity {
	return predicate.Identity(sql.FieldHasSuffix(FieldProviderUID, v))
}

// ProviderUIDEqualFold applies the EqualFold predicate on the "provider_uid" field.
func ProviderUIDEqualFold(v string) predicate.Identity {
	return predicate.Identity(sql.FieldEqualFold(FieldProviderUID, v))
}

// ProviderUIDContainsFold applies the ContainsFold predicate on the "provider_uid" field.
func ProviderUIDContainsFold(v string) predicate.Identity {
	return predicate.Identity(sql.FieldContainsFold(FieldProviderUID, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.Identity {
	return predicate.Identity(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.Identity {
	return predicate.Identity(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Identity {
	return predicate.Identity(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Identity {
	return predicate.Identity(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Identity {
	return predicate.Identity(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Identity {
	return predicate.Identity(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Identity {
	return predicate.Identity(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Identity {
	return predicate.Identity(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Identity {
	return predicate.Identity(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Identity {
	return predicate.Identity(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Identity {
	return predicate.Identity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Identity {
	return predicate.Identity(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Identity) predicate.Identity {
	return predicate.Identity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Identity) predicate.Identity {
	return predicate.Identity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Identity) predicate.Identity {
	return predicate.Identity(sql.NotPredicates(p))
}
