# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x03llm\"\x96\x01\n\nLLMRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07room_id\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x11\n\tuser_text\x18\x04 \x01(\t\x12\x0f\n\x07is_last\x18\x05 \x01(\x08\x12\x0b\n\x03seq\x18\x06 \x01(\x03\x12\x0e\n\x06\x63\x61ncel\x18\x07 \x01(\x08\x12\x0f\n\x07user_id\x18\x08 \x01(\t\"\xf9\x01\n\x0bLLMResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07room_id\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x15\n\rresponse_text\x18\x04 \x01(\t\x12\x10\n\x08is_final\x18\x05 \x01(\x08\x12\x0b\n\x03seq\x18\x06 \x01(\x03\x12\x12\n\nerror_code\x18\x07 \x01(\t\x12\x12\n\nevent_type\x18\x08 \x01(\t\x12\x14\n\x0ctool_call_id\x18\t \x01(\t\x12\x11\n\ttool_name\x18\n \x01(\t\x12\x16\n\x0etool_arguments\x18\x0b \x01(\t\x12\x13\n\x0btool_result\x18\x0c \x01(\t\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xdf\x01\n\x13HealthCheckResponse\x12\x36\n\x06status\x18\x01 \x01(\x0e\x32&.llm.HealthCheckResponse.ServingStatus\x12\x17\n\x0f\x61\x63tive_sessions\x18\x02 \x01(\x05\x12\x15\n\rprovider_name\x18\x03 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x04 \x01(\x01\"H\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x12\x0c\n\x08\x44\x45GRADED\x10\x03\x32\x83\x01\n\nLLMService\x12\x33\n\nChatStream\x12\x0f.llm.LLMRequest\x1a\x10.llm.LLMResponse(\x01\x30\x01\x12@\n\x0bHealthCheck\x12\x17.llm.HealthCheckRequest\x1a\x18.llm.HealthCheckResponseB\x13Z\x11\x62\x61\x63kend/proto/llmb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021backend/proto/llm'
  _globals['_LLMREQUEST']._serialized_start=19
  _globals['_LLMREQUEST']._serialized_end=169
  _globals['_LLMRESPONSE']._serialized_start=172
  _globals['_LLMRESPONSE']._serialized_end=421
  _globals['_HEALTHCHECKREQUEST']._serialized_start=423
  _globals['_HEALTHCHECKREQUEST']._serialized_end=460
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=463
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=686
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=614
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=686
  _globals['_LLMSERVICE']._serialized_start=689
  _globals['_LLMSERVICE']._serialized_end=820
# @@protoc_insertion_point(module_scope)
