// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: llm.proto

package llm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LLMService_ChatStream_FullMethodName = "/llm.LLMService/ChatStream"
)

// LLMServiceClient is the client API for LLMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LLMServiceClient interface {
	ChatStream(ctx context.Context, opts ...grpc.CallOption) (LLMService_ChatStreamClient, error)
}

type lLMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMServiceClient(cc grpc.ClientConnInterface) LLMServiceClient {
	return &lLMServiceClient{cc}
}

func (c *lLMServiceClient) ChatStream(ctx context.Context, opts ...grpc.CallOption) (LLMService_ChatStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &LLMService_ServiceDesc.Streams[0], LLMService_ChatStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &lLMServiceChatStreamClient{stream}
	return x, nil
}

type LLMService_ChatStreamClient interface {
	Send(*LLMRequest) error
	Recv() (*LLMResponse, error)
	grpc.ClientStream
}

type lLMServiceChatStreamClient struct {
	grpc.ClientStream
}

func (x *lLMServiceChatStreamClient) Send(m *LLMRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *lLMServiceChatStreamClient) Recv() (*LLMResponse, error) {
	m := new(LLMResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LLMServiceServer is the server API for LLMService service.
// All implementations must embed UnimplementedLLMServiceServer
// for forward compatibility
type LLMServiceServer interface {
	ChatStream(LLMService_ChatStreamServer) error
	mustEmbedUnimplementedLLMServiceServer()
}

// UnimplementedLLMServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLLMServiceServer struct {
}

func (UnimplementedLLMServiceServer) ChatStream(LLMService_ChatStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedLLMServiceServer) mustEmbedUnimplementedLLMServiceServer() {}

// UnsafeLLMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMServiceServer will
// result in compilation errors.
type UnsafeLLMServiceServer interface {
	mustEmbedUnimplementedLLMServiceServer()
}

func RegisterLLMServiceServer(s grpc.ServiceRegistrar, srv LLMServiceServer) {
	s.RegisterService(&LLMService_ServiceDesc, srv)
}

func _LLMService_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LLMServiceServer).ChatStream(&lLMServiceChatStreamServer{stream})
}

type LLMService_ChatStreamServer interface {
	Send(*LLMResponse) error
	Recv() (*LLMRequest, error)
	grpc.ServerStream
}

type lLMServiceChatStreamServer struct {
	grpc.ServerStream
}

func (x *lLMServiceChatStreamServer) Send(m *LLMResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *lLMServiceChatStreamServer) Recv() (*LLMRequest, error) {
	m := new(LLMRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LLMService_ServiceDesc is the grpc.ServiceDesc for LLMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llm.LLMService",
	HandlerType: (*LLMServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _LLMService_ChatStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "llm.proto",
}
