// Code generated by ent, DO NOT EDIT.

package roommember

import (
	"echat-backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldLTE(FieldID, id))
}

// RoomID applies equality check predicate on the "room_id" field. It's identical to RoomIDEQ.
func RoomID(v uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldEQ(FieldRoomID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldEQ(FieldUserID, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldEQ(FieldUsername, v))
}

// JoinedAt applies equality check predicate on the "joined_at" field. It's identical to JoinedAtEQ.
func JoinedAt(v time.Time) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldEQ(FieldJoinedAt, v))
}

// LeftAt applies equality check predicate on the "left_at" field. It's identical to LeftAtEQ.
func LeftAt(v time.Time) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldEQ(FieldLeftAt, v))
}

// RoomIDEQ applies the EQ predicate on the "room_id" field.
func RoomIDEQ(v uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldEQ(FieldRoomID, v))
}

// RoomIDNEQ applies the NEQ predicate on the "room_id" field.
func RoomIDNEQ(v uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldNEQ(FieldRoomID, v))
}

// RoomIDIn applies the In predicate on the "room_id" field.
func RoomIDIn(vs ...uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldIn(FieldRoomID, vs...))
}

// RoomIDNotIn applies the NotIn predicate on the "room_id" field.
func RoomIDNotIn(vs ...uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldNotIn(FieldRoomID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldNotIn(FieldUserID, vs...))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldContainsFold(FieldUsername, v))
}

// JoinedAtEQ applies the EQ predicate on the "joined_at" field.
func JoinedAtEQ(v time.Time) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldEQ(FieldJoinedAt, v))
}

// JoinedAtNEQ applies the NEQ predicate on the "joined_at" field.
func JoinedAtNEQ(v time.Time) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldNEQ(FieldJoinedAt, v))
}

// JoinedAtIn applies the In predicate on the "joined_at" field.
func JoinedAtIn(vs ...time.Time) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldIn(FieldJoinedAt, vs...))
}

// JoinedAtNotIn applies the NotIn predicate on the "joined_at" field.
func JoinedAtNotIn(vs ...time.Time) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldNotIn(FieldJoinedAt, vs...))
}

// JoinedAtGT applies the GT predicate on the "joined_at" field.
func JoinedAtGT(v time.Time) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldGT(FieldJoinedAt, v))
}

// JoinedAtGTE applies the GTE predicate on the "joined_at" field.
func JoinedAtGTE(v time.Time) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldGTE(FieldJoinedAt, v))
}

// JoinedAtLT applies the LT predicate on the "joined_at" field.
func JoinedAtLT(v time.Time) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldLT(FieldJoinedAt, v))
}

// JoinedAtLTE applies the LTE predicate on the "joined_at" field.
func JoinedAtLTE(v time.Time) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldLTE(FieldJoinedAt, v))
}

// LeftAtEQ applies the EQ predicate on the "left_at" field.
func LeftAtEQ(v time.Time) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldEQ(FieldLeftAt, v))
}

// LeftAtNEQ applies the NEQ predicate on the "left_at" field.
func LeftAtNEQ(v time.Time) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldNEQ(FieldLeftAt, v))
}

// LeftAtIn applies the In predicate on the "left_at" field.
func LeftAtIn(vs ...time.Time) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldIn(FieldLeftAt, vs...))
}

// LeftAtNotIn applies the NotIn predicate on the "left_at" field.
func LeftAtNotIn(vs ...time.Time) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldNotIn(FieldLeftAt, vs...))
}

// LeftAtGT applies the GT predicate on the "left_at" field.
func LeftAtGT(v time.Time) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldGT(FieldLeftAt, v))
}

// LeftAtGTE applies the GTE predicate on the "left_at" field.
func LeftAtGTE(v time.Time) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldGTE(FieldLeftAt, v))
}

// LeftAtLT applies the LT predicate on the "left_at" field.
func LeftAtLT(v time.Time) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldLT(FieldLeftAt, v))
}

// LeftAtLTE applies the LTE predicate on the "left_at" field.
func LeftAtLTE(v time.Time) predicate.RoomMember {
	return predicate.RoomMember(sql.FieldLTE(FieldLeftAt, v))
}

// LeftAtIsNil applies the IsNil predicate on the "left_at" field.
func LeftAtIsNil() predicate.RoomMember {
	return predicate.RoomMember(sql.FieldIsNull(FieldLeftAt))
}

// LeftAtNotNil applies the NotNil predicate on the "left_at" field.
func LeftAtNotNil() predicate.RoomMember {
	return predicate.RoomMember(sql.FieldNotNull(FieldLeftAt))
}

// HasRoom applies the HasEdge predicate on the "room" edge.
func HasRoom() predicate.RoomMember {
	return predicate.RoomMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoomTable, RoomColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoomWith applies the HasEdge predicate on the "room" edge with a given conditions (other predicates).
func HasRoomWith(preds ...predicate.Room) predicate.RoomMember {
	return predicate.RoomMember(func(s *sql.Selector) {
		step := newRoomStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.RoomMember {
	return predicate.RoomMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.RoomMember {
	return predicate.RoomMember(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RoomMember) predicate.RoomMember {
	return predicate.RoomMember(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RoomMember) predicate.RoomMember {
	return predicate.RoomMember(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RoomMember) predicate.RoomMember {
	return predicate.RoomMember(sql.NotPredicates(p))
}
