// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: asr.proto

package asr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AudioChunk 音频数据
type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`     // 用于区分不同语音会话，避免多个用户或房间的上下文串扰
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`              // 标识当前音频所属房间，便于后端做房间级广播
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`        // 表示发送音频的客户端标识
	Pcm           []byte                 `protobuf:"bytes,4,opt,name=pcm,proto3" json:"pcm,omitempty"`                                  // 原始 PCM16 音频数据，按小端有符号短整型编码
	SampleRate    int32                  `protobuf:"varint,5,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // 给出音频采样率，通常应为 16000
	IsLast        bool                   `protobuf:"varint,6,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`             // 标记当前块是否为本次会话的最后一块
	Seq           int64                  `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`                                 // 用于保持消息顺序，便于后端做乱序处理或重试
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_asr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{0}
}

func (x *AudioChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AudioChunk) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AudioChunk) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AudioChunk) GetPcm() []byte {
	if x != nil {
		return x.Pcm
	}
	return nil
}

func (x *AudioChunk) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *AudioChunk) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// TranscriptAudioChunk 表示 ASR 服务返回的一段识别结果
type TranscriptAudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 对应输入音频块所属会话
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`          // 对应输入音频块所属房间
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`    // 对应输入音频块所属客户端
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`                            // 当前块对应的识别文本结果
	IsFinal       bool                   `protobuf:"varint,5,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`      // 表示当前文本是否为最终结果
	Seq           int64                  `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`                             // 对应输入音频块的序号，便于客户端按顺序拼接
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptAudioChunk) Reset() {
	*x = TranscriptAudioChunk{}
	mi := &file_asr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptAudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptAudioChunk) ProtoMessage() {}

func (x *TranscriptAudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptAudioChunk.ProtoReflect.Descriptor instead.
func (*TranscriptAudioChunk) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{1}
}

func (x *TranscriptAudioChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TranscriptAudioChunk) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *TranscriptAudioChunk) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TranscriptAudioChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscriptAudioChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *TranscriptAudioChunk) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

var File_asr_proto protoreflect.FileDescriptor

const file_asr_proto_rawDesc = "" +
	"\n" +
	"\tasr.proto\x12\x03asr\"\xbf\x01\n" +
	"\n" +
	"AudioChunk\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x10\n" +
	"\x03pcm\x18\x04 \x01(\fR\x03pcm\x12\x1f\n" +
	"\vsample_rate\x18\x05 \x01(\x05R\n" +
	"sampleRate\x12\x17\n" +
	"\ais_last\x18\x06 \x01(\bR\x06isLast\x12\x10\n" +
	"\x03seq\x18\a \x01(\x03R\x03seq\"\xac\x01\n" +
	"\x14TranscriptAudioChunk\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x19\n" +
	"\bis_final\x18\x05 \x01(\bR\aisFinal\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x03R\x03seq2T\n" +
	"\n" +
	"AsrService\x12F\n" +
	"\x14RecognizeAudioStream\x12\x0f.asr.AudioChunk\x1a\x19.asr.TranscriptAudioChunk(\x010\x01B\x13Z\x11backend/proto/asrb\x06proto3"

var (
	file_asr_proto_rawDescOnce sync.Once
	file_asr_proto_rawDescData []byte
)

func file_asr_proto_rawDescGZIP() []byte {
	file_asr_proto_rawDescOnce.Do(func() {
		file_asr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asr_proto_rawDesc), len(file_asr_proto_rawDesc)))
	})
	return file_asr_proto_rawDescData
}

var file_asr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_asr_proto_goTypes = []any{
	(*AudioChunk)(nil),           // 0: asr.AudioChunk
	(*TranscriptAudioChunk)(nil), // 1: asr.TranscriptAudioChunk
}
var file_asr_proto_depIdxs = []int32{
	0, // 0: asr.AsrService.RecognizeAudioStream:input_type -> asr.AudioChunk
	1, // 1: asr.AsrService.RecognizeAudioStream:output_type -> asr.TranscriptAudioChunk
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_asr_proto_init() }
func file_asr_proto_init() {
	if File_asr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asr_proto_rawDesc), len(file_asr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asr_proto_goTypes,
		DependencyIndexes: file_asr_proto_depIdxs,
		MessageInfos:      file_asr_proto_msgTypes,
	}.Build()
	File_asr_proto = out.File
	file_asr_proto_goTypes = nil
	file_asr_proto_depIdxs = nil
}
