// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/vad.proto

package vad

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pcm           []byte                 `protobuf:"bytes,1,opt,name=pcm,proto3" json:"pcm,omitempty"`                                  // 原始 16-bit 有符号 PCM 音频字节流（int16 little-endian，单声道）
	SampleRate    int32                  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // PCM 音频的采样率，例如 8000、16000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VadRequest) Reset() {
	*x = VadRequest{}
	mi := &file_proto_vad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VadRequest) ProtoMessage() {}

func (x *VadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VadRequest.ProtoReflect.Descriptor instead.
func (*VadRequest) Descriptor() ([]byte, []int) {
	return file_proto_vad_proto_rawDescGZIP(), []int{0}
}

func (x *VadRequest) GetPcm() []byte {
	if x != nil {
		return x.Pcm
	}
	return nil
}

func (x *VadRequest) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type VadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Speech        bool                   `protobuf:"varint,1,opt,name=speech,proto3" json:"speech,omitempty"` // true 表示检测到人声活动，false 表示静音或非人声
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`  // 置信度分数，1.0=高度确信有人声，0.0=高度确信为静音
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VadResponse) Reset() {
	*x = VadResponse{}
	mi := &file_proto_vad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VadResponse) ProtoMessage() {}

func (x *VadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VadResponse.ProtoReflect.Descriptor instead.
func (*VadResponse) Descriptor() ([]byte, []int) {
	return file_proto_vad_proto_rawDescGZIP(), []int{1}
}

func (x *VadResponse) GetSpeech() bool {
	if x != nil {
		return x.Speech
	}
	return false
}

func (x *VadResponse) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_proto_vad_proto protoreflect.FileDescriptor

const file_proto_vad_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/vad.proto\x12\x03vad\"?\n" +
	"\n" +
	"VadRequest\x12\x10\n" +
	"\x03pcm\x18\x01 \x01(\fR\x03pcm\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\";\n" +
	"\vVadResponse\x12\x16\n" +
	"\x06speech\x18\x01 \x01(\bR\x06speech\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score2<\n" +
	"\n" +
	"VadService\x12.\n" +
	"\tVadDetect\x12\x0f.vad.VadRequest\x1a\x10.vad.VadResponseB\x13Z\x11backend/proto/vadb\x06proto3"

var (
	file_proto_vad_proto_rawDescOnce sync.Once
	file_proto_vad_proto_rawDescData []byte
)

func file_proto_vad_proto_rawDescGZIP() []byte {
	file_proto_vad_proto_rawDescOnce.Do(func() {
		file_proto_vad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vad_proto_rawDesc), len(file_proto_vad_proto_rawDesc)))
	})
	return file_proto_vad_proto_rawDescData
}

var file_proto_vad_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_vad_proto_goTypes = []any{
	(*VadRequest)(nil),  // 0: vad.VadRequest
	(*VadResponse)(nil), // 1: vad.VadResponse
}
var file_proto_vad_proto_depIdxs = []int32{
	0, // 0: vad.VadService.VadDetect:input_type -> vad.VadRequest
	1, // 1: vad.VadService.VadDetect:output_type -> vad.VadResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_vad_proto_init() }
func file_proto_vad_proto_init() {
	if File_proto_vad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vad_proto_rawDesc), len(file_proto_vad_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vad_proto_goTypes,
		DependencyIndexes: file_proto_vad_proto_depIdxs,
		MessageInfos:      file_proto_vad_proto_msgTypes,
	}.Build()
	File_proto_vad_proto = out.File
	file_proto_vad_proto_goTypes = nil
	file_proto_vad_proto_depIdxs = nil
}
