// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/vad.proto

package vad

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VadService_VadDetect_FullMethodName = "/vad.VadService/VadDetect"
)

// VadServiceClient is the client API for VadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VadService 语音活动检测（VAD）服务
// 接收 PCM 音频帧，返回该帧是否包含人声
type VadServiceClient interface {
	// VadDetect 检测一段 PCM 音频中是否有人声活动
	VadDetect(ctx context.Context, in *VadRequest, opts ...grpc.CallOption) (*VadResponse, error)
}

type vadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVadServiceClient(cc grpc.ClientConnInterface) VadServiceClient {
	return &vadServiceClient{cc}
}

func (c *vadServiceClient) VadDetect(ctx context.Context, in *VadRequest, opts ...grpc.CallOption) (*VadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VadResponse)
	err := c.cc.Invoke(ctx, VadService_VadDetect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VadServiceServer is the server API for VadService service.
// All implementations must embed UnimplementedVadServiceServer
// for forward compatibility.
//
// VadService 语音活动检测（VAD）服务
// 接收 PCM 音频帧，返回该帧是否包含人声
type VadServiceServer interface {
	// VadDetect 检测一段 PCM 音频中是否有人声活动
	VadDetect(context.Context, *VadRequest) (*VadResponse, error)
	mustEmbedUnimplementedVadServiceServer()
}

// UnimplementedVadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVadServiceServer struct{}

func (UnimplementedVadServiceServer) VadDetect(context.Context, *VadRequest) (*VadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VadDetect not implemented")
}
func (UnimplementedVadServiceServer) mustEmbedUnimplementedVadServiceServer() {}
func (UnimplementedVadServiceServer) testEmbeddedByValue()                    {}

// UnsafeVadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VadServiceServer will
// result in compilation errors.
type UnsafeVadServiceServer interface {
	mustEmbedUnimplementedVadServiceServer()
}

func RegisterVadServiceServer(s grpc.ServiceRegistrar, srv VadServiceServer) {
	// If the following call panics, it indicates UnimplementedVadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VadService_ServiceDesc, srv)
}

func _VadService_VadDetect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VadServiceServer).VadDetect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VadService_VadDetect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VadServiceServer).VadDetect(ctx, req.(*VadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VadService_ServiceDesc is the grpc.ServiceDesc for VadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vad.VadService",
	HandlerType: (*VadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VadDetect",
			Handler:    _VadService_VadDetect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/vad.proto",
}
